package br.com.fiap.mscustomers.utils;

import br.com.fiap.mscustomers.entity.Customer;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;

public class CustomerUtils {

	public static Customer createFakeCustomer() {
		Customer customer = new Customer();
		customer.setCpf("822.685.230-71"); //Random CPF generated by 4devs.com.br site
		customer.setFullName("Dummy customer");
		customer.setEmail("dummycustomer@email.com");
		customer.setZipCode("00000-000");
		customer.setAddress("Rua dos Bobos, 0");
		customer.setCity("São Paulo");
		customer.setState("São Paulo");
		customer.setCountry("Brasil");

		return customer;
	}

	public static Customer createFakeCustomer(String cpf, String name) {
		Customer customer = new Customer();
		customer.setCpf(cpf);
		customer.setFullName(name);
		customer.setEmail("dummycustomer@email.com");
		customer.setZipCode("00000-000");
		customer.setAddress("Rua dos Bobos, 0");
		customer.setCity("São Paulo");
		customer.setState("São Paulo");
		customer.setCountry("Brasil");

		return customer;
	}

	public static String asJsonString(final Object object) throws JsonProcessingException {
		return new ObjectMapper().writeValueAsString(object);
	}
}
